version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network
    #environment:
      #- MONGO_INITDB_ROOT_USERNAME=admin
      #- MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      #- ME_CONFIG_BASICAUTH_USERNAME=admin
      #- ME_CONFIG_BASICAUTH_PASSWORD=tribes
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
        driver: bridge