server:
  port: 8091
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml

spring:
  mongodb:
    embedded:
      version: "4.4.1"
  data:
    mongodb:
      uuid-representation: standard
      database: productdb